---
blank_issues_enabled: false
contact_links:
  - name: "ğŸ› Bug Report"
    url: https://github.com/link-society/issues/issues/new?template=bug-report.md
    about: Create a report to help us improve
  - name: "âœ¨ Feature Request"
    url: https://github.com/link-society/issues/issues/new?template=feature-request.md
    about: Propose a new idea for this project
  - name: "ğŸ™ Help Wanted"
    url: https://github.com/link-society/issues/issues/new?template=help-wanted.md
    about: Let us help you the best way we can

